development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: activities_development
  pool:     5
  username: mihai
  password:
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: activities_test
  pool:     5
  username: mihai
  password:
  template: template0
